config/routes.rb
Rails.application.routes.draw do
  resources :materials
  resources :items
  resources :suppliers
  resources :suppliers

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :supplier
  has_many :materials
  accepts_nested_attributes_for :materials, allow_destroy: true
end

app/models/material.rb
class Material < ActiveRecord::Base
  belongs_to :item
  belongs_to :supplier

  after_commit :update_item_price

  def update_item_price
    return false unless self.item.present?
    
    item = self.item
    item.master_price = item.materials.sum(:price) * 1.5
    item.cost_price = item.materials.sum(:price)
    item.save
  end
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  belongs_to :supplyable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to edit_item_path(@item), notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to edit_item_path(@item), notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:state, :sku, :master_price, :cost_price, :note, :supplier_id, materials_attributes: [:_destroy, :id, :name, :weight, :amount, :price, :note, :item_id, :supplier_id])
    end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_material, only: [:show, :edit, :update, :destroy]

  # GET /materials
  # GET /materials.json
  def index
    @materials = Material.all
  end

  # GET /materials/1
  # GET /materials/1.json
  def show
  end

  # GET /materials/new
  def new
    @material = Material.new
  end

  # GET /materials/1/edit
  def edit
  end

  # POST /materials
  # POST /materials.json
  def create
    @material = Material.new(material_params)

    respond_to do |format|
      if @material.save
        format.html { redirect_to @material, notice: 'Material was successfully created.' }
        format.json { render :show, status: :created, location: @material }
      else
        format.html { render :new }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materials/1
  # PATCH/PUT /materials/1.json
  def update
    respond_to do |format|
      if @material.update(material_params)
        format.html { redirect_to @material, notice: 'Material was successfully updated.' }
        format.json { render :show, status: :ok, location: @material }
      else
        format.html { render :edit }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materials/1
  # DELETE /materials/1.json
  def destroy
    @material.destroy
    respond_to do |format|
      format.html { redirect_to materials_url, notice: 'Material was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def material_params
      params.require(:material).permit(:name, :weight, :amount, :price, :note, :item_id, :supplier_id)
    end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: [:show, :edit, :update, :destroy]

  # GET /suppliers
  # GET /suppliers.json
  def index
    @suppliers = Supplier.all
  end

  # GET /suppliers/1
  # GET /suppliers/1.json
  def show
  end

  # GET /suppliers/new
  def new
    @supplier = Supplier.new
  end

  # GET /suppliers/1/edit
  def edit
  end

  # POST /suppliers
  # POST /suppliers.json
  def create
    @supplier = Supplier.new(supplier_params)

    respond_to do |format|
      if @supplier.save
        format.html { redirect_to @supplier, notice: 'Supplier was successfully created.' }
        format.json { render :show, status: :created, location: @supplier }
      else
        format.html { render :new }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suppliers/1
  # PATCH/PUT /suppliers/1.json
  def update
    respond_to do |format|
      if @supplier.update(supplier_params)
        format.html { redirect_to @supplier, notice: 'Supplier was successfully updated.' }
        format.json { render :show, status: :ok, location: @supplier }
      else
        format.html { render :edit }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suppliers/1
  # DELETE /suppliers/1.json
  def destroy
    @supplier.destroy
    respond_to do |format|
      format.html { redirect_to suppliers_url, notice: 'Supplier was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supplier
      @supplier = Supplier.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supplier_params
      params.require(:supplier).permit(:name, :supplyable_id, :supplyable_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/items/_form.html.erb
<div class="row">
  <%= simple_form_for(@item) do |f| %>
    <%= f.error_notification %>
    <div class="col-sm-4">
      <div class="form-inputs" class="col-sm-4">
        <%= f.input :sku %>
        <%= f.input :master_price %>
        <%= f.input :cost_price %>
        <%= f.input :note %>
        <%= f.association :supplier %>
        <%= f.collection_radio_buttons :state, [["new", "New"] ,["sold", "Sold"], ["reparing", "Repairing"]], :first, :last, wrapper_html: {id: "xxx"} %>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="form-inputs" class="col-sm-4">
        <%= f.nested_fields_for :materials do |ff| %>
          <div class="row">
            <%= ff.input :name, wrapper_html: { class: 'col-xs-8' } %>
            <%= ff.association :supplier, wrapper_html: { class: 'col-xs-4' } %>
          </div>
          <div class="row">
            <%= ff.input :weight, wrapper_html: { class: 'col-xs-4' } %>
            <%= ff.input :amount, wrapper_html: { class: 'col-xs-4' } %>
            <%= ff.input :price, wrapper_html: { class: 'col-xs-4' } %>
          </div>
          <!-- <%= ff.input :note %> -->
          <%= ff.remove_nested_fields_link('Remove', class: 'btn btn-danger', role: 'button') %>
          <hr>
        <% end %>
        <%= f.add_nested_fields_link(:materials, 'Add Material', class: 'btn btn-primary', role: 'button') %>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="form-actions">
        <%= f.button :submit %>
      </div>
    </div>
  <% end %>
</div>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Items</h1>

<table class="table">
  <thead>
    <tr>
      <th>Sku</th>
      <th>Master price</th>
      <th>Cost price</th>
      <th>Note</th>
      <th>Supplier</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.sku %></td>
        <td><%= item.master_price %></td>
        <td><%= item.cost_price %></td>
        <td><%= item.note %></td>
        <td><%= item.supplier.name %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path, class: "btn btn-primary" %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sku:</strong>
  <%= @item.sku %>
</p>

<p>
  <strong>Master price:</strong>
  <%= @item.master_price %>
</p>

<p>
  <strong>Cost price:</strong>
  <%= @item.cost_price %>
</p>

<p>
  <strong>Note:</strong>
  <%= @item.note %>
</p>

<p>
  <strong>Supplier:</strong>
  <%= @item.supplier %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cgems</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/materials/_form.html.erb
<%= simple_form_for(@material) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :weight %>
    <%= f.input :amount %>
    <%= f.input :price %>
    <%= f.input :note %>
    <%= f.association :item %>
    <%= f.association :supplier %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/materials/edit.html.erb
<h1>Editing Material</h1>

<%= render 'form' %>

<%= link_to 'Show', @material %> |
<%= link_to 'Back', materials_path %>

app/views/materials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Materials</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Weight</th>
      <th>Amount</th>
      <th>Price</th>
      <th>Note</th>
      <th>Item</th>
      <th>Supplier</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @materials.each do |material| %>
      <tr>
        <td><%= material.name %></td>
        <td><%= material.weight %></td>
        <td><%= material.amount %></td>
        <td><%= material.price %></td>
        <td><%= material.note %></td>
        <td><%= material.item %></td>
        <td><%= material.supplier %></td>
        <td><%= link_to 'Show', material %></td>
        <td><%= link_to 'Edit', edit_material_path(material) %></td>
        <td><%= link_to 'Destroy', material, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Material', new_material_path %>

app/views/materials/new.html.erb
<h1>New Material</h1>

<%= render 'form' %>

<%= link_to 'Back', materials_path %>

app/views/materials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @material.name %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @material.weight %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @material.amount %>
</p>

<p>
  <strong>Price:</strong>
  <%= @material.price %>
</p>

<p>
  <strong>Note:</strong>
  <%= @material.note %>
</p>

<p>
  <strong>Item:</strong>
  <%= @material.item %>
</p>

<p>
  <strong>Supplier:</strong>
  <%= @material.supplier %>
</p>

<%= link_to 'Edit', edit_material_path(@material) %> |
<%= link_to 'Back', materials_path %>

app/views/suppliers/_form.html.erb
<%= simple_form_for(@supplier) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/suppliers/edit.html.erb
<h1>Editing Supplier</h1>

<%= render 'form' %>

<%= link_to 'Show', @supplier %> |
<%= link_to 'Back', suppliers_path %>

app/views/suppliers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Suppliers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Supplyable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @suppliers.each do |supplier| %>
      <tr>
        <td><%= supplier.name %></td>
        <td><%= supplier.supplyable %></td>
        <td><%= link_to 'Show', supplier %></td>
        <td><%= link_to 'Edit', edit_supplier_path(supplier) %></td>
        <td><%= link_to 'Destroy', supplier, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Supplier', new_supplier_path %>

app/views/suppliers/new.html.erb
<h1>New Supplier</h1>

<%= render 'form' %>

<%= link_to 'Back', suppliers_path %>

app/views/suppliers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @supplier.name %>
</p>

<p>
  <strong>Supplyable:</strong>
  <%= @supplier.supplyable %>
</p>

<%= link_to 'Edit', edit_supplier_path(@supplier) %> |
<%= link_to 'Back', suppliers_path %>